fieldLayouts:
  2ab4b96a-6044-459c-b4b7-7aed0f11bdd0:
    tabs:
      -
        elements:
          -
            fieldUid: 57e741e7-dc8e-4e79-90ee-b15a840b8e37 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fff4c499-7fd9-4657-9395-7aa99c768dfc # Feature image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 54e29fb3-8d88-44bd-ba19-60be1ea3601b # Post Content
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0862cea9-8276-4009-b21c-ed1fca9c702e # Post Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Post Content'
        sortOrder: 1
handle: default
hasTitleField: false
name: Blog
section: e5f3dfd6-ba18-47d1-ab55-e6734f5eb6f5 # Blog
sortOrder: 1
titleFormat: 'Title Field Label'
titleTranslationKeyFormat: null
titleTranslationMethod: site
