defaultPlacement: end
fieldLayouts:
  805644d5-7c16-4d02-aca6-d4494299bbc7:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Контент
        sortOrder: 1
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  00271a83-c8ad-4864-b686-aa96658c722f: # Craft CMS
    hasUrls: true
    template: blog/_category
    uriFormat: 'blog/category/{slug}'
structure:
  maxLevels: 1
  uid: 7744fd29-21a7-47ea-82ab-014d25d67336
