dateModified: 1648869924
email:
  fromEmail: nightmarelie@gmail.com
  fromName: 'Craft CMS'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    01ef494b-c370-43e4-bbe3-2d5a6bb07a04: 'Craft CMS' # Craft CMS
    4ab9de46-8152-453e-bbea-5420fa31d3f4: Common # Common
    6c08ce07-b661-4c40-bca8-05e4cf2eabae: Image # Image
    43c68f31-5efc-4cd8-b119-76ecd5dc7550: Text # Text
    54e29fb3-8d88-44bd-ba19-60be1ea3601b: 'Post Content' # Post Content
    57d479f8-21be-4448-a8ba-0381c3dc8102: Blog # Blog
    57e741e7-dc8e-4e79-90ee-b15a840b8e37: Summary # Summary
    186d891b-9a56-43ea-8e79-b48cb235cd02: 'Blog Categories' # Blog Categories
    00271a83-c8ad-4864-b686-aa96658c722f: 'Craft CMS' # Craft CMS
    624c5a89-6ecf-48fb-9c1e-e23d91579e41: 'Blog Post Fields' # Blog Post Fields
    0862cea9-8276-4009-b21c-ed1fca9c702e: 'Post Categories' # Post Categories
    95497185-afca-4387-9cb2-337403d0a37c: Blog # Blog
    e5f3dfd6-ba18-47d1-ab55-e6734f5eb6f5: Blog # Blog
    f0b90b3a-6bf5-4a99-adae-bb7d6e29d86f: Text # Text
    fff4c499-7fd9-4657-9395-7aa99c768dfc: 'Feature image' # Feature image
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: 'Craft CMS'
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
