fieldLayouts:
  8d9ec439-723e-4fef-8be9-b394fb922a93:
    tabs:
      -
        elements:
          -
            fieldUid: 55ab0ded-b1ce-47d7-9cf8-bc0e0d620deb # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Site Description'
        sortOrder: 1
handle: siteInformation
name: 'Site Information'
sortOrder: 1
