defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  00271a83-c8ad-4864-b686-aa96658c722f: # Craft CMS
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
